config/routes.rb
Rails.application.routes.draw do
  get 'prototypes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :prototypes do
  resources :comments, only: :create
  root to: 'prototypes#index'

end
  root to: 'prototypes#index'
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :prototype, presence: true
  validates :user, presence: true
  belongs_to :prototype
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belong_to :user
  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
  belongs_to :user
  has_one_attached : image
  has_many :comments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :name, presence: true
         validates :profile, presence: true
         validates :occupation, presence: true
         validates :position, presence: true
         has_many :prototypes
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    '@comment = Comment.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype)
    else
      '@prototype = @comment.prototype
      '@comments = @prototype.comments
      render "prototypes/show"
    end
  end
end

private
 def comment_params
  params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
 end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  def index
    @prototypes = prototype.includes(:user)
  end
  def new
    #プロトタイプオブジェクトを生成
    @prototype = Prototype.new
  end
  
  def create
    @prtotype = current_user.prototypes.new(prototype_params)
    if @prototype.save
      redirect_to prototypes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

    private
  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image)
  end
  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end
  def edit
    @prototype = Prototype.find(params[:id])
  end
  def update
   @prototype = Prototype.find(params[:id])
   @prototype.update(prototype_params)
   if @prototype.save
    redirect_to root_path
   else
    render :edit, status: :unprocessable_entity
   end
  end
  def destroy
    @prototype = Prototype.find(params[:id])
    @prototype.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace39604</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
    <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <% if user_signed_in? %>
    <div class="nav__right">
    <%= link_to "ログアウト", root_path, class: :nav__logout %>
    <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
    </div>
    <div class="nav__right">
    <%= link_to "ログイン", user_session_path, class: :nav__btn %>
    <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
    <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
    </div>
    <% end %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: モデル名, local: true do |f|%>
  <div class="field">
    <%= f.label :hoge, "プロトタイプの名称" %><br />
    <%= f.text_field :hoge, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :hoge, "キャッチコピー" %><br />
    <%= f.text_area :hoge, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :hoge, "コンセプト" %><br />
    <%= f.text_area :hoge, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :hoge, "プロトタイプの画像" %><br />
    <%= f.file_field :hoge, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id) %>
  <div class="card__body">
    <%= link_to prototype.title, root_path, class: :card__title%>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to prototype.user.name, root_path, class: :card__user %>
  </div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<%# ログインしているときは以下を表示する %>
<% if user_signed_in? %>
<div class="greeting">
こんにちは、
<%= link_to "#{current_user.name}さん", root_path, class: :greeting__link%>
</div>
<%= render "form" %>
<% end %>
<%# // ログインしているときは上記を表示する %>

<%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
<%= render partial: 'prototype', collection: @prototypes %>

app/views/users/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to @prototype.user.name, root_path, class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), data: { turbo_method: :delete }, class: :prototype__btn %>
        </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <% if user_signed_in? && current_user.id == @prototypes.user_id %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%# <%= form_with model: モデル名,local: true do |f|%>
            <div class="field">
              <%# <%= f.label :hoge, "コメント" %><br />
              <%# <%= f.text_field :hoge, id:"comment_content" %>
            </div>
            <div class="actions">
              <%# <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <%# <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <li class="comments_list">
            <% @comments.each do |comment| %>
            <li class="comments_list">
            <% @comments.each do |comment| %>
            <p>
            <%= comment.content %>
            <%= link_to "(#{@prototype.user.name})", root_path, class: :comment_user %>
            </p>
            <% end %>
          </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>